### ISSUE TITLE
java.lang.NoSuchMethodError: 'java.lang.String org.bukkit.Server.getServerName()' on Paper-Spigot 1.15.2 with LC 2.4

### ISSUE THREAD

**Issue by rautamiekka** [TBMCPlugins/LimitedCreative#4]
```
[20:45:04 WARN]: [LimitedCreative] Plugin LimitedCreative v2.4 generated an exception while executing task 65
java.lang.NoSuchMethodError: 'java.lang.String org.bukkit.Server.getServerName()'
        at de.jaschastarke.bukkit.tools.stats.PiwikStatistics$1.run(PiwikStatistics.java:118) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-105]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-105]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-105]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
```

Haven't tested on vanilla Spigot 1.15.2. Doesn't happen with Paper-Spigot 1.14.4.

**Comment by NorbiPeti** [comment]
I'll see if I can fix it easily but disabling metrics in the config should remove that error.

**Comment by rautamiekka** [comment]
> I'll see if I can fix it easily but disabling metrics in the config should remove that error.

Confirmed, that fixes it.
